monitor.libcamera.rules = [
  {
    matches = [
      {
        "device.name" = "~libcamera.*"
      }
    ]
    actions = {
      update-props = {
        "video.rotation" = 180
      }
    }
  }
]

monitor.v4l2.rules = [
  {
    matches = [
      {
        "node.name" = "~v4l2_input.*"
      }
    ]
    actions = {
      update-props = {
        "video.rotation" = 180
      }
    }
  }
]
